AWSTemplateFormatVersion: 2010-09-09
Description: Root stack template 
Parameters:
  WebServerImage:
    Type: AWS::EC2::Image::Id
    Description: AMI for the web server stack
  WebServerBucket:
    Type: String
Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/jones-user-data/598982fecbc7b70c139a957e31f09de6.template
  WebServerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-1.amazonaws.com/jones-user-data/c3d54c77b8db537e101331c445ae4735.template
      Parameters:
        ImageId:
          Ref: WebServerImage
        WebServerSecurityGroup:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.WebServerSecurityGroup
        SubnetId:
          Fn::Select:
          - 0
          - Fn::Split:
            - ','
            - Fn::GetAtt:
              - NetworkStack
              - Outputs.PublicSubnets
        WebServerBucket:
          Ref: WebServerBucket
